### ISSUE TITLE
Sample codes required

### ISSUE THREAD

**Issue by kayazinc** [True-cc/RadialMenu#1]
Require sample codes or documentation for customization.  Thanks.

**Comment by SelfMadeSystem** [comment]
Hey, I didn't make it fully functional. It's not really a working prototype. If you want a working prototype, check out https://github.com/SelfMadeSystem/GUI-Stuffs (although it's in Java w/ LWJGL (OpenGL))

**Comment by SelfMadeSystem** [comment]
Either way, it's all basically SVG and everything's hardcoded. If I were to remake it (which I might), I'd definitely make it differently.

**Comment by SelfMadeSystem** [comment]
hey I've been remaking it in the [CompleteRecode](https://github.com/SelfMadeSystem/RadialMenu/tree/CompleteRecode) branch if you want to check it out. no documentation yet, but there is a basic example in `main.ts`. imo, the code is also better organized.

**Comment by SelfMadeSystem** [comment]
I'm just using canvas instead of weirdness with SVG & React. @kayazinc
